version: '3.8'

services:
  main-db:
    image: 'postgres:14.3-alpine'
    container_name: main-api-db
    restart: on-failure
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TITLE}
  book-tracker-service:
    restart: on-failure
    ports:
      - ${TRACKER_LOCAL_PORT}:${TRACKER_DOCKER_PORT}
    container_name: book-tracker
    environment:
      APP_RETURNRATE: 7
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:${POSTGRES_DOCKER_PORT}/library_db
    build:
      context: /book-tracker-service
      dockerfile: Dockerfile
    depends_on:
      - main-db
  book-storage-service:
    restart: on-failure
    ports:
      - ${STORAGE_LOCAL_PORT}:${STORAGE_DOCKER_PORT}
    container_name: book-storage
    environment:
      APP_CLIENTS_TRACKER_URL: book-tracker-service:${TRACKER_DOCKER_PORT}
      APP_CLIENTS_TRACKER_NAME: ${TRACKER_NAME}
      APP_CLIENTS_TRACKER_PATH: ${TRACKER_PATH}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:${POSTGRES_DOCKER_PORT}/library_db
    build:
      context: /book-storage-service
      dockerfile: Dockerfile
    depends_on:
      - book-tracker-service
