server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123123
    username: modsen
    url: jdbc:postgresql://localhost:5430/library_db
  liquibase:
    enabled: true
    change-log: db.changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  return_rate: 7