server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123123
    username: modsen
    url: jdbc:postgresql://localhost:5430/library_db
  liquibase:
    enabled: true
    change-log: db.changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  scheduling-check-expiration: "0 * * * * *"
  returnRate: 8