server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.LongSerializer
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123123
    username: modsen
    url: jdbc:postgresql://localhost:5430/library_db
  liquibase:
    enabled: true
    change-log: db.changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  token:
    expireTime: 150000
  clients:
    user-client:
      url: 127.0.0.1:8082
      name: user-client
      path: /api/v1/users
    tracker:
      url: 127.0.0.1:8081
      name: tracker-client
      path: /api/v1/tracking